import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Terms of Service',
  description: 'AI Toolbox terms of service — the rules and conditions governing your use of our platform.',
};

export default function TermsPage() {
  return (
    <div className="container mx-auto px-4 py-12 max-w-3xl">
      <div className="mb-8">
        <h1 className="text-3xl font-bold mb-2">Terms of Service</h1>
        <p className="text-muted-foreground text-sm">
          Last updated: {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}
        </p>
      </div>

      <div className="prose prose-sm dark:prose-invert max-w-none space-y-8 text-foreground">
        <section>
          <h2 className="text-xl font-semibold mb-3">1. Acceptance of Terms</h2>
          <p className="text-muted-foreground leading-relaxed">
            By accessing or using AI Toolbox (&quot;the Service&quot;), you agree to be bound by
            these Terms of Service. If you do not agree to these terms, please do not use the
            Service. These terms apply to all visitors, users, and anyone who accesses or uses
            the Service.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-3">2. Description of Service</h2>
          <p className="text-muted-foreground leading-relaxed">
            AI Toolbox is a web platform providing access to artificial intelligence utilities
            including, but not limited to: AI-powered chat, text summarisation, image generation,
            and code explanation. The Service is powered by third-party AI models from OpenAI
            and Replicate.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-3">3. User Accounts</h2>
          <p className="text-muted-foreground leading-relaxed">
            To access most features, you must create an account. You are responsible for:
          </p>
          <ul className="mt-3 space-y-1.5 text-muted-foreground">
            <li>• Maintaining the confidentiality of your account credentials</li>
            <li>• All activities that occur under your account</li>
            <li>• Notifying us immediately of any unauthorised use of your account</li>
            <li>• Providing accurate, current, and complete information during registration</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-3">4. Acceptable Use</h2>
          <p className="text-muted-foreground leading-relaxed">
            You agree to use the Service only for lawful purposes. You must not use the Service to:
          </p>
          <ul className="mt-3 space-y-1.5 text-muted-foreground">
            <li>• Generate harmful, illegal, or misleading content</li>
            <li>• Violate any applicable local, national, or international laws</li>
            <li>• Infringe on the intellectual property rights of others</li>
            <li>• Attempt to gain unauthorised access to any part of the Service</li>
            <li>• Reverse-engineer, decompile, or disassemble any part of the Service</li>
            <li>• Circumvent usage limits or subscription restrictions</li>
            <li>• Generate adult content, violence, or material harmful to minors</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-3">5. Subscription Plans and Billing</h2>
          <p className="text-muted-foreground leading-relaxed">
            AI Toolbox offers a free tier with daily usage limits and optional paid plans with
            higher limits. For paid plans:
          </p>
          <ul className="mt-3 space-y-1.5 text-muted-foreground">
            <li>• Subscriptions are billed monthly or annually in advance</li>
            <li>• Payments are processed securely via Stripe</li>
            <li>• You may cancel at any time; access continues until the billing period ends</li>
            <li>• Refunds are issued at our discretion for billing errors</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-3">6. Intellectual Property</h2>
          <p className="text-muted-foreground leading-relaxed">
            You retain ownership of the content you provide as input to the Service. The outputs
            generated by AI models may be used freely, subject to the terms of the underlying
            AI providers (OpenAI, Replicate). The Service software, design, and branding are
            owned by AI Toolbox and protected by copyright law.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-3">7. Disclaimer of Warranties</h2>
          <p className="text-muted-foreground leading-relaxed">
            The Service is provided &quot;as is&quot; without warranty of any kind. We do not warrant
            that the Service will be error-free, uninterrupted, or that AI-generated content
            will be accurate, complete, or suitable for any particular purpose. AI outputs
            should be reviewed critically before use in important decisions.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-3">8. Limitation of Liability</h2>
          <p className="text-muted-foreground leading-relaxed">
            To the maximum extent permitted by law, AI Toolbox shall not be liable for any
            indirect, incidental, special, or consequential damages arising from your use of,
            or inability to use, the Service. Our total liability to you shall not exceed the
            amount you paid us in the past 12 months.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-3">9. Termination</h2>
          <p className="text-muted-foreground leading-relaxed">
            We may terminate or suspend your account at any time, with or without notice, for
            violations of these Terms. You may terminate your account at any time by contacting
            support. Upon termination, your right to use the Service ceases immediately.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-3">10. Contact</h2>
          <p className="text-muted-foreground leading-relaxed">
            Questions about these Terms? Contact us at{' '}
            <a
              href="mailto:legal@ai-toolbox.example.com"
              className="text-primary underline hover:no-underline"
            >
              legal@ai-toolbox.example.com
            </a>
            .
          </p>
        </section>
      </div>
    </div>
  );
}
